#!/bin/bash
set -e

if [[ ! "$VLC_ANDROID_VERSION" =~ ^[0-9\.]+$ ]]
then
    echo "Invalid vlc android version: $VLC_ANDROID_VERSION"
    exit 1
fi

if [[ ! "$VERSION" =~ ^[0-9\.]+$ ]]
then
    echo "Skip building for vlc-android-sdk: $VERSION"
    exit 1
fi

PROJECT_DIR=`pwd`
ANDROID_NDK="$HOME"/ndk
rm -rf "$ANDROID_NDK"
mkdir -p "$ANDROID_NDK"
cd "$ANDROID_NDK"
ANDROID_NDK_VERSION=r18b
ANDROID_NDK_SHA256=4f61cbe4bbf6406aa5ef2ae871def78010eed6271af72de83f8bd0b07a9fd3fd
echo "Download android ndk" && wget -q https://dl.google.com/android/repository/android-ndk-$ANDROID_NDK_VERSION-linux-x86_64.zip
echo "$ANDROID_NDK_SHA256" android-ndk-$ANDROID_NDK_VERSION-linux-x86_64.zip | sha256sum -c
echo "Extract android ndk" && unzip -q android-ndk-$ANDROID_NDK_VERSION-linux-x86_64.zip
rm -f android-ndk-$ANDROID_NDK_VERSION-linux-x86_64.zip
mv android-ndk-$ANDROID_NDK_VERSION/** .
rm -rf android-ndk-$ANDROID_NDK_VERSION
cd "$PROJECT_DIR"
echo "ndk.dir=$ANDROID_NDK" > local.properties
echo "sdk.dir=$ANDROID_SDK" >> local.properties
GRADLE_VERSION=5.4.1
GRADLE_SHA256=7bdbad1e4f54f13c8a78abc00c26d44dd8709d4aedb704d913fb1bb78ac025dc
echo "Download gradle" && wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
echo "$GRADLE_SHA256" gradle-$GRADLE_VERSION-bin.zip | sha256sum -c
echo "Extract gradle" && unzip -q gradle-$GRADLE_VERSION-bin.zip
rm -f gradle-$GRADLE_VERSION-bin.zip
cd gradle-$GRADLE_VERSION
./bin/gradle --offline wrapper
cd "$PROJECT_DIR"
mkdir gradle
mv gradle-$GRADLE_VERSION/gradle/wrapper/ gradle
mv gradle-$GRADLE_VERSION/gradlew .
chmod a+x gradlew
SRC_MAIN_DIR="src/main"
JNILIBS_DIR="$SRC_MAIN_DIR"/jniLibs
JAVA_DIR="$SRC_MAIN_DIR"/java
mkdir -p "$SRC_MAIN_DIR"
mkdir -p "$JNILIBS_DIR"
mkdir -p "$JAVA_DIR"
for ARCHITECTURE in armeabi-v7a arm64-v8a x86_64 x86
do
    wget https://github.com/Stremio/vlc-android-sdk/releases/download/"$VERSION"-"$ARCHITECTURE"/libvlc-"$ARCHITECTURE"-jni.zip
    unzip -q libvlc-"$ARCHITECTURE"-jni.zip
    rm -f libvlc-"$ARCHITECTURE"-jni.zip
    cp -r libvlc-jni/* "$JNILIBS_DIR"
    rm -rf libvlc-jni
done
git clone "https://code.videolan.org/videolan/vlc-android.git" -b "$VLC_ANDROID_VERSION" vlc-android
cp vlc-android/libvlc/AndroidManifest.xml "$SRC_MAIN_DIR"
cp -r vlc-android/libvlc/src/ "$JAVA_DIR"
mv "$JAVA_DIR"/src/* "$JAVA_DIR"
rm -rf "$JAVA_DIR"/src
rm -rf vlc-android
