#!/bin/bash
set -e

VLC_ANDROID_VERSION=$1
ARCHITECTURE=$2

if [[ ! "$VLC_ANDROID_VERSION" =~ ^[0-9\.]+$ ]]
then
    echo "Invalid vlc android version: $VLC_ANDROID_VERSION"
    exit 1
fi

if [[ "$ARCHITECTURE" != "armeabi-v7a" && 
    "$ARCHITECTURE" != "arm64-v8a" &&
    "$ARCHITECTURE" != "x86_64" && 
    "$ARCHITECTURE" != "x86" ]]
then
    echo "Invalid architecture: $ARCHITECTURE"
    exit 2
fi

cd "$HOME"
git clone "https://code.videolan.org/videolan/vlc-android.git" -b "$VLC_ANDROID_VERSION" vlc-android
cd vlc-android
sh compile.sh -a "$ARCHITECTURE" -l --release --no-ml
cd "$HOME"
mkdir libvlc-jni
unzip vlc-android/libvlc/build/outputs/aar/*.aar jni/* -d libvlc-jni
mv libvlc-jni/jni/* libvlc-jni
rm -rf libvlc-jni/jni
zip -r libvlc-"$ARCHITECTURE"-jni.zip libvlc-jni
