#!/bin/bash
set -e

VLC_ANDROID_VERSION=$1
ARCHITECTURE=$2

if [[ ! "$VLC_ANDROID_VERSION" =~ ^[0-9\.]+$ ]]
then
    echo "Invalid vlc android version: $VLC_ANDROID_VERSION"
    exit 1
fi

if [[ "$ARCHITECTURE" != "armeabi-v7a" && 
    "$ARCHITECTURE" != "arm64-v8a" &&
    "$ARCHITECTURE" != "x86_64" && 
    "$ARCHITECTURE" != "x86" ]]
then
    echo "Invalid architecture: $ARCHITECTURE"
    exit 2
fi

cd "$HOME"
git clone "https://code.videolan.org/videolan/vlc-android.git" -b "$VLC_ANDROID_VERSION" vlc-android
cd vlc-android
sh compile.sh -a "$ARCHITECTURE" -l --release --no-ml
cd ..

OUTPUT_DIR="libvlc-jni"
mkdir -p "$OUTPUT_DIR"
unzip vlc-android/libvlc/build/outputs/aar/*.aar jni/* -d "$OUTPUT_DIR"
mv "$OUTPUT_DIR"/jni/* "$OUTPUT_DIR"
rm -rf "$OUTPUT_DIR"/jni
zip -r libvlc-"$ARCHITECTURE"-jni.zip "$OUTPUT_DIR"
