#!/bin/bash

VERSION=4.0.0
for ARCHITECTURE in armeabi-v7a arm64-v8a x86_64 x86
do
    wget https://github.com/Stremio/vlc-android-sdk/releases/download/$VERSION-$ARCHITECTURE/libvlc-$ARCHITECTURE.zip
    unzip libvlc-$ARCHITECTURE.zip
    yes | cp -r libvlc/* .
    rm libvlc-$ARCHITECTURE.zip
    rm -rf ./libvlc
done
